\ $Id$

\ Cross-compiler environments

<WORDLISTS ONLY FORTH ALSO ROOT DEFINITIONS

\ Load code into the cross-compiler
: <CROSS-COMPILER
    <WORDLISTS ONLY FORTH ALSO CROSS ALSO CROSS-COMPILER DEFINITIONS ;
: CROSS-COMPILER>
    WORDLISTS> ;

\ Cross-compile code into the target image
: <TARGET
    <WORDLISTS ONLY ALSO CROSS ALSO CROSS-COMPILER ALSO TARGET DEFINITIONS ;
: TARGET> CROSS-COMPILER> ;

WORDLISTS>
